In [1]:
import numpy as np

In [2]:
myarr=np.array([2,10,24,12])

In [3]:
myarr

array([ 2, 10, 24, 12])

In [4]:
print(type(myarr))

<class 'numpy.ndarray'>


In [5]:
myarr.dtype

dtype('int64')

In [6]:
myarr=np.array([2,10,24,12],np.int64)

In [7]:
myarr.dtype

dtype('int64')

In [8]:
myarr=np.array([2,10,24,12.3])

In [9]:
myarr.dtype

dtype('float64')

In [10]:
for i in myarr:
    print(i)

2.0
10.0
24.0
12.3


In [11]:
print(myarr[0:3])

[ 2. 10. 24.]


In [12]:
zeros=np.zeros((2,5))

In [13]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
zeros=np.ones((2,5))

In [15]:
zeros

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
ide=np.eye(4)

In [17]:
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
ide=np.identity(4)

In [19]:
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
rand=np.random.random((2,5))
rand*10

array([[3.36212311, 4.92445749, 9.53883719, 0.6871969 , 5.68795503],
       [0.11407166, 9.94251892, 1.84953097, 4.7087012 , 1.23446579]])

In [21]:
rand.size

10

In [22]:
rand.shape

(2, 5)

In [23]:
rand.reshape(5,2)

array([[0.33621231, 0.49244575],
       [0.95388372, 0.06871969],
       [0.5687955 , 0.01140717],
       [0.99425189, 0.1849531 ],
       [0.47087012, 0.12344658]])

In [24]:
myarr

array([ 2. , 10. , 24. , 12.3])

In [25]:
print(max(myarr))

24.0


In [26]:
print(min(myarr))

2.0


In [27]:
print(myarr*2)

[ 4.  20.  48.  24.6]
