# Advance Operations With Business Examples

In [5]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
#  Data Structure: [restaurant_id,2021,2022,2023,2024]
sales_data=np.array([
    [1, 150000, 180000, 220000, 250000], # paradise biryani
    [2, 120000, 140000, 160000, 200000], # Beijing bites
    [3, 200000, 230000, 260000, 300000], # Pizza hub
    [4, 180000, 210000, 240000, 270000], # Burger point
    [5, 160000, 185000, 205000, 230000]  # Chai point
])

In [8]:
# Find first 3 restaurant details
print(" first 3 restaurant details\n",sales_data[0:3])

 first 3 restaurant details
 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 200000]
 [     3 200000 230000 260000 300000]]


In [10]:
#  Total sales per year
print(np.sum(sales_data, axis=0)) # axis=0 , add coloumn wise like for 2021- 150000+120000+200000+180000+160000= 810000 and so on...

[     15  810000  945000 1085000 1250000]


In [17]:
# Minimum sales per 
min_sales=np.min(sales_data[:, 1:], axis=1)
print(min_sales)

[150000 120000 200000 180000 160000]
